/**
 * Agent Worker Loop — Real Execution
 *
 * Agents now perform real operations based on their skills:
 * - deploy  → Calls Vercel API to deploy the project
 * - code    → Creates/writes files in GitHub repo
 * - design  → Generates CSS from project design tokens
 * - content → Structured content template
 * - shop    → Shop configuration notes
 * - planning→ Planning document (already generated by wizard)
 *
 * All outputs go to review_notes for human approval.
 */

import { getAdminToken, apiCall } from "./pocketbase";
import { type Task, type Agent, type Project } from "@/types";
import { triggerDeployment } from "./vercel-api";
import { createFileInRepo } from "./github-api";

/* ───────── helpers ───────── */

async function getAuth(): Promise<string> {
  return getAdminToken();
}

async function getAgents(token: string): Promise<Agent[]> {
  const data = await apiCall("/api/collections/agents/records?perPage=500", { token }) as { items: Agent[] };
  return (data.items || []).map((a: Agent) => ({
    ...a,
    skills: Array.isArray(a.skills) ? a.skills : [],
    department: a.department || "",
  }));
}

async function getPendingTasks(token: string): Promise<Task[]> {
  const data = await apiCall("/api/collections/tasks/records?perPage=500", { token }) as { items: Task[] };
  const all = data.items || [];
  return all.filter((t: Task) => t.status === "todo" && t.assignee);
}

async function getProject(token: string, id: string): Promise<Project | null> {
  try {
    const data = await apiCall(`/api/collections/projects/records/${id}`, { token });
    return data as unknown as Project;
  } catch {
    return null;
  }
}

async function getCompanySettings(token: string): Promise<Record<string, string> | null> {
  try {
    const data = await apiCall("/api/collections/company_settings/records?perPage=1", { token }) as { items: any[] };
    return data.items?.[0] || null;
  } catch {
    return null;
  }
}

async function updateTask(token: string, id: string, updates: Record<string, unknown>): Promise<void> {
  await apiCall(`/api/collections/tasks/records/${id}`, { method: "PATCH", token, body: updates });
}

async function updateAgent(token: string, id: string, updates: Record<string, unknown>): Promise<void> {
  await apiCall(`/api/collections/agents/records/${id}`, { method: "PATCH", token, body: updates });
}

async function logActivity(token: string, action: string, entityType: string, entityId: string, entityName: string, details: string): Promise<void> {
  try {
    await apiCall("/api/collections/activity_logs/records", {
      method: "POST",
      token,
      body: { action, entity_type: entityType, entity_id: entityId, entity_name: entityName, details },
    });
  } catch { /* logging must never break the loop */ }
}

/* ───────── real handlers ───────── */

const handlers: Record<string, (task: Task, agent: Agent, token: string) => Promise<{ output: string; notes: string }>> = {

  /** DEPLOY — Trigger Vercel deployment for the project */
  async deploy(task, agent, token) {
    const settings = await getCompanySettings(token);
    const vercelToken = settings?.vercel_token;

    if (!task.project) {
      return {
        output: "No project linked to this task.",
        notes: `Agent ${agent.name} attempted to deploy but the task has no associated project. Link a project first.`,
      };
    }

    const project = await getProject(token, task.project);
    if (!project?.vercel_project_id) {
      return {
        output: "No Vercel project configured.",
        notes: `Agent ${agent.name} attempted to deploy "${project?.name || "project"}" but no Vercel project ID is set. Configure it in project settings first.`,
      };
    }

    if (!vercelToken) {
      return {
        output: "No Vercel token configured.",
        notes: `Agent ${agent.name} attempted to deploy but the company has no Vercel API token. Add it in Settings > Integrations.`,
      };
    }

    try {
      const deploy = await triggerDeployment({
        token: vercelToken,
        projectId: project.vercel_project_id,
        teamId: project.vercel_team_id || settings?.vercel_team_id || undefined,
        target: "production",
      });

      const deployUrl = deploy.url ? `https://${deploy.url}` : "Deploy triggered";
      return {
        output: JSON.stringify({ deploymentId: deploy.id, url: deployUrl }, null, 2),
        notes: `Agent ${agent.name} triggered a production deployment for "${project.name}". Deployment ID: ${deploy.id}. Review the URL before approving.`,
      };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return {
        output: `Deploy failed: ${msg}`,
        notes: `Agent ${agent.name} attempted to deploy "${project.name}" but encountered an error: ${msg}. Check the Vercel connection.`,
      };
    }
  },

  /** CODE — Create/write files in GitHub repo */
  async code(task, agent, token) {
    const settings = await getCompanySettings(token);
    const githubToken = settings?.github_token;

    if (!task.project) {
      return {
        output: "No project linked.",
        notes: `Agent ${agent.name} attempted to write code but the task has no associated project.`,
      };
    }

    const project = await getProject(token, task.project);
    if (!project?.github_repo) {
      return {
        output: "No GitHub repo configured.",
        notes: `Agent ${agent.name} attempted to write code for "${project?.name || "project"}" but no GitHub repo is linked. Set github_repo in project settings.`,
      };
    }

    if (!githubToken) {
      return {
        output: "No GitHub token configured.",
        notes: `Agent ${agent.name} attempted to write code but the company has no GitHub token. Add it in Settings > Integrations.`,
      };
    }

    // Parse "owner/repo" from github_repo field
    const repoMatch = project.github_repo.match(/^([^\/]+)\/([^\/]+)$/);
    if (!repoMatch) {
      return {
        output: "Invalid repo format.",
        notes: `Agent ${agent.name} found github_repo "${project.github_repo}" but it's not in "owner/repo" format.`,
      };
    }
    const [, owner, repo] = repoMatch;

    // Generate file path from task title
    const fileName = task.title.toLowerCase().replace(/[^a-z0-9]+/g, "-") + ".tsx";
    const filePath = `src/app/${fileName}`;

    const componentName = task.title.replace(/[^a-zA-Z0-9]/g, "");
    const codeContent = `// Auto-generated by Mission Control — Agent ${agent.name}\n// Task: ${task.title}\n// Review before approving\n\nexport default function ${componentName}Page() {\n  return (\n    <div className="p-8">\n      <h1 className="text-2xl font-bold">${task.title}</h1>\n      <p>${task.description || "Implementation goes here."}</p>\n    </div>\n  );\n}\n`;

    try {
      await createFileInRepo(githubToken, owner, repo, filePath, codeContent, `feat: ${task.title} [agent: ${agent.name}]`);
      return {
        output: codeContent,
        notes: `Agent ${agent.name} created \`${filePath}\` in ${project.github_repo}. Review the code before approving.`,
      };
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      return {
        output: `File creation failed: ${msg}`,
        notes: `Agent ${agent.name} attempted to write \`${filePath}\` but failed: ${msg}. Check GitHub token permissions (needs \`repo\` scope).`,
      };
    }
  },

  /** DESIGN — Generate CSS from project design tokens */
  async design(task, agent, token) {
    if (!task.project) {
      return {
        output: "No project linked.",
        notes: `Agent ${agent.name} attempted to generate design tokens but no project is linked.`,
      };
    }

    const project = await getProject(token, task.project);
    const css = `/* Auto-generated by Mission Control — Agent ${agent.name} */\n/* Task: ${task.title} */\n/* Project: ${project?.name || "unknown"} */\n\n:root {\n  --color-primary: ${project?.color_primary || "#3b82f6"};\n  --color-secondary: ${project?.color_secondary || "#64748b"};\n  --color-accent: ${project?.color_accent || "#f59e0b"};\n  --color-background: ${project?.color_background || "#0a0a0f"};\n  --font-heading: ${project?.font_heading || "Inter, sans-serif"};\n  --font-body: ${project?.font_body || "Inter, sans-serif"};\n  --design-vibe: ${project?.design_vibe || "modern"};\n}\n`;

    return {
      output: css,
      notes: `Agent ${agent.name} generated CSS design tokens for "${project?.name || "project"}". Review the colors, fonts, and vibe before approving.`,
    };
  },

  /** CONTENT — Structured content template */
  async content(task, agent, token) {
    const content = `# ${task.title}\n\n${task.description || ""}\n\n---\nGenerated by Agent ${agent.name}\nReview before publishing.\n`;
    return {
      output: content,
      notes: `Agent ${agent.name} drafted content for "${task.title}". Review tone, accuracy, and completeness before approving.`,
    };
  },

  /** SHOP — Generate structured e-commerce configuration */
  async shop(task, agent, token) {
    const project = task.project ? await getProject(token, task.project) : null;
    const shopConfig = {
      project: project?.name || "Unnamed Shop",
      generated_by: agent.name,
      timestamp: new Date().toISOString(),
      sections: {
        products: {
          categories: ["General"],
          variants_enabled: true,
          inventory_tracking: true,
        },
        payments: {
          stripe: { enabled: false, test_mode: true },
          paypal: { enabled: false },
          bank_transfer: { enabled: false },
        },
        shipping: {
          flat_rate: { enabled: true, cost: "5.00", currency: project?.budget ? "EUR" : "USD" },
          free_shipping_threshold: "50.00",
        },
        taxes: {
          vat_enabled: true,
          vat_rate: "19%",
          included_in_price: true,
        },
        checkout: {
          guest_checkout: true,
          cart_abandonment: true,
          email_notifications: true,
        },
      },
      recommendations: [
        "Enable Stripe for card payments",
        "Set up shipping zones for target markets",
        "Configure tax rules per region",
        "Add product categories before launch",
      ],
    };

    return {
      output: JSON.stringify(shopConfig, null, 2),
      notes: `Agent ${agent.name} generated e-commerce configuration for "${project?.name || task.title}". Review payment gateways, shipping rules, and tax settings before approving.`,
    };
  },

  /** PLANNING — Generate structured project plan */
  async planning(task, agent, token) {
    const project = task.project ? await getProject(token, task.project) : null;
    const plan = {
      project: project?.name || task.title,
      generated_by: agent.name,
      timestamp: new Date().toISOString(),
      phases: [
        { name: "Discovery", duration: "3-5 days", deliverables: ["Requirements doc", "User stories", "Tech stack decision"], status: "pending" },
        { name: "Design", duration: "5-7 days", deliverables: ["Wireframes", "Visual design", "Design system"], status: "pending" },
        { name: "Development", duration: "2-4 weeks", deliverables: ["Frontend", "Backend", "APIs", "Database"], status: "pending" },
        { name: "Testing", duration: "3-5 days", deliverables: ["Unit tests", "Integration tests", "Bug fixes"], status: "pending" },
        { name: "Deployment", duration: "1-2 days", deliverables: ["CI/CD setup", "Production deploy", "Domain config"], status: "pending" },
        { name: "Launch", duration: "1 day", deliverables: ["Go-live", "Monitoring", "Analytics"], status: "pending" },
      ],
      milestones: [
        { name: "Design Approval", target: "Week 2", blocker: false },
        { name: "MVP Complete", target: "Week 4", blocker: true },
        { name: "Soft Launch", target: "Week 5", blocker: false },
      ],
      risks: [
        "Scope creep — define MVP strictly",
        "Integration delays — test early",
        "Performance — optimize before launch",
      ],
    };

    return {
      output: JSON.stringify(plan, null, 2),
      notes: `Agent ${agent.name} created a project plan for "${project?.name || task.title}". Review phases, milestones, and risk mitigations before approving.`,
    };
  },
};

/* ───────── main cycle ───────── */

export async function runWorkerCycle(): Promise<{ executed: number; review_count: number; errors: string[] }> {
  const errors: string[] = [];
  let executed = 0;
  let reviewCount = 0;

  try {
    const token = await getAuth();
    const agents = await getAgents(token);
    const tasks = await getPendingTasks(token);
    const agentMap = new Map(agents.map((a) => [a.id, a]));

    for (const task of tasks) {
      try {
        const agent = task.assignee ? agentMap.get(task.assignee) : undefined;
        if (!agent) {
          errors.push(`Task ${task.id}: no agent found for assignee ${task.assignee}`);
          continue;
        }
        if (agent.paused) {
          errors.push(`Task ${task.id}: agent ${agent.name} is paused`);
          continue;
        }

        const taskType = task.type || "planning";
        const handler = handlers[taskType] || handlers.planning;

        // Mark in_progress + agent working
        await updateTask(token, task.id, {
          status: "in_progress",
          updated: new Date().toISOString(),
        });
        await updateAgent(token, agent.id, {
          status: "working",
          current_task: task.id,
        });

        // Execute real operation
        const { output, notes } = await handler(task, agent, token);

        // Move to review
        await updateTask(token, task.id, {
          status: "review",
          review_notes: `${notes}\n\n--- Output ---\n${output}`.substring(0, 5000),
          updated: new Date().toISOString(),
        });
        await updateAgent(token, agent.id, {
          status: "idle",
          current_task: null,
        });

        await logActivity(
          token,
          "review",
          "task",
          task.id,
          task.title,
          `Agent ${agent.name} finished "${task.title}" (${taskType}) and submitted for review.`
        );

        reviewCount++;
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        errors.push(`Task ${task.id}: ${msg}`);
      }
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    errors.push(`Worker cycle failed: ${msg}`);
  }

  return { executed, review_count: reviewCount, errors };
}
