/**
 * Agent Worker Loop
 *
 * Polls PocketBase for assigned tasks, executes them based on type,
 * moves them to "review" with feedback notes, and logs activity.
 *
 * Human reviews the output, then approves (status → "done") or rejects
 * (status → "todo" with feedback).
 */

import { getAdminToken, apiCall } from "./pocketbase";
import { type Task, type Agent } from "@/types";

// Task execution handlers — placeholder, will be replaced with real AI calls
const handlers: Record<string, (task: Task, agent: Agent) => Promise<{ output: string; notes: string }>> = {
  async code(task, agent) {
    // TODO: integrate with Gemini / Ollama for real code generation
    return {
      output: `// Generated by ${agent.name}\n// Task: ${task.title}\n\nconsole.log("Hello from Mission Control!");`,
      notes: `Agent ${agent.name} wrote ${task.title}. Review the code output before approving.`,
    };
  },
  async design(task, agent) {
    return {
      output: `Design mockup for ${task.title}`,
      notes: `Agent ${agent.name} created design concepts. Check the visual output.`,
    };
  },
  async content(task, agent) {
    return {
      output: `Content draft for ${task.title}`,
      notes: `Agent ${agent.name} wrote content. Review for tone and accuracy.`,
    };
  },
  async deploy(task, agent) {
    return {
      output: `Deployment config for ${task.title}`,
      notes: `Agent ${agent.name} prepared deployment. Verify settings before pushing.`,
    };
  },
  async planning(task, agent) {
    return {
      output: `Planning document for ${task.title}`,
      notes: `Agent ${agent.name} completed planning. Review the strategy.`,
    };
  },
  async shop(task, agent) {
    return {
      output: `Shop configuration for ${task.title}`,
      notes: `Agent ${agent.name} configured shop settings. Review before going live.`,
    };
  },
};

/* ───────────────────────── helpers ───────────────────────── */

async function getAuth(): Promise<string> {
  return getAdminToken();
}

async function getAgents(token: string): Promise<Agent[]> {
  const data = await apiCall("/api/collections/agents/records?perPage=500", { token }) as { items: Agent[] };
  return (data.items || []).map((a: Agent) => ({
    ...a,
    skills: Array.isArray(a.skills) ? a.skills : [],
    department: a.department || "",
  }));
}

async function getPendingTasks(token: string): Promise<Task[]> {
  const data = await apiCall("/api/collections/tasks/records?perPage=500", { token }) as { items: Task[] };
  const all = data.items || [];
  return all.filter((t: Task) => t.status === "todo" && t.assignee);
}

async function updateTask(token: string, id: string, updates: Record<string, unknown>): Promise<void> {
  await apiCall(`/api/collections/tasks/records/${id}`, {
    method: "PATCH",
    token,
    body: updates,
  });
}

async function updateAgent(token: string, id: string, updates: Record<string, unknown>): Promise<void> {
  await apiCall(`/api/collections/agents/records/${id}`, {
    method: "PATCH",
    token,
    body: updates,
  });
}

async function logActivity(token: string, action: string, entityType: string, entityId: string, entityName: string, details: string): Promise<void> {
  try {
    await apiCall("/api/collections/activity_logs/records", {
      method: "POST",
      token,
      body: { action, entity_type: entityType, entity_id: entityId, entity_name: entityName, details },
    });
  } catch {
    // logging must never break the loop
  }
}

/* ───────────────────────── cycle ───────────────────────── */

export async function runWorkerCycle(): Promise<{ executed: number; review_count: number; errors: string[] }> {
  const errors: string[] = [];
  let executed = 0;
  let reviewCount = 0;

  try {
    const token = await getAuth();
    const agents = await getAgents(token);
    const tasks = await getPendingTasks(token);
    const agentMap = new Map(agents.map((a) => [a.id, a]));

    for (const task of tasks) {
      try {
        const agent = task.assignee ? agentMap.get(task.assignee) : undefined;
        if (!agent) {
          errors.push(`Task ${task.id}: no agent found for assignee ${task.assignee}`);
          continue;
        }
        if (agent.paused) {
          errors.push(`Task ${task.id}: agent ${agent.name} is paused`);
          continue;
        }

        const taskType = task.type || "planning";
        const handler = handlers[taskType] || handlers.planning;

        // 1) Mark in_progress + agent working
        await updateTask(token, task.id, {
          status: "in_progress",
          updated: new Date().toISOString(),
        });
        await updateAgent(token, agent.id, {
          status: "working",
          current_task: task.id,
        });

        // 2) Execute (AI generation or other work)
        const { output, notes } = await handler(task, agent);

        // 3) Move to review — human must approve
        await updateTask(token, task.id, {
          status: "review",
          review_notes: `${notes}\n\n--- Output ---\n${output}`.substring(0, 5000), // cap length
          updated: new Date().toISOString(),
        });
        await updateAgent(token, agent.id, {
          status: "idle",
          current_task: null,
        });

        // 4) Log
        await logActivity(
          token,
          "review",
          "task",
          task.id,
          task.title,
          `Agent ${agent.name} finished "${task.title}" and submitted it for review.`
        );

        reviewCount++;
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        errors.push(`Task ${task.id}: ${msg}`);
      }
    }
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    errors.push(`Worker cycle failed: ${msg}`);
  }

  return { executed, review_count: reviewCount, errors };
}
